services:
  postgres:
    image: postgres:16
    container_name: cmp_postgres
    restart: always
    environment:
      POSTGRES_USER: cmp_user
      POSTGRES_PASSWORD: cmp_password
      POSTGRES_DB: customer_meeting_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: